#! /usr/bin/env python

# IMPORTANT: "my_model.h5" and "min_max_scalar_data.npy" from save_files folder are needed to make predictions

import source.forecast as forecast
import source.load_data as data
import traceback
import sys

if __name__ == '__main__':

    # Forecast for x days without a test set
    forecast.forecast(test_keys_present=False, use_test_keys_for_forcast=False)